language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t guillsav/multi-docker -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true guillsav/multi-docker npm test -- --coverage

after_success:
  - docker build -t guillsav/multi-client ./client
  - docker build -t guillsav/multi-nginx ./nginx
  - docker build -t guillsav/multi-server ./server
  - docker build -t guillsav/multi-worker ./worker
  # Log in to the docker CLI
  - docker login -u "$DOCKER_USERNAME"  --password-stdin "$DOCKER_PASSWORD"
  # Take those images and push them to docker hub
  - docker push guillsav/multi-client
  - docker push guillsav/multi-nginx
  - docker push guillsav/multi-server
  - docker push guillsav/multi-worker
